name: sync-from-gitee
run-name: 从 gitee 同步
on:
  push:
  schedule:
    - cron: '0 0 * * *'

jobs:
  sync-from-gitee:
    runs-on: ubuntu-22.04
    env:
      TARGET_REPO_URL: "https://gitee.com/bling_yshs/ys-dio-pic-repo.git" # 目标仓库的URL
      TARGET_REPO_BRANCH: "master"
      DESTINATION_FOLDER: "ys-dio-pic-repo"
      CLONE_TEMP_DIR: "clone-temp"
    steps:
      - name: 克隆当前仓库
        uses: actions/checkout@v4

      - name: 配置 git 用户
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: 获取远端最新 commit SHA
        id: get_remote_sha
        run: |
          SHA=$(git ls-remote "${{ env.TARGET_REPO_URL }}" "${{ env.TARGET_REPO_BRANCH }}" | cut -f1)
          echo "sha=$SHA" >> $GITHUB_OUTPUT

      - name: 缓存目标仓库
        uses: actions/cache@v4
        with:
          path: ${{ env.CLONE_TEMP_DIR }}
          key: ${{ runner.os }}-clone_temp-${{ steps.get_remote_sha.outputs.sha }}
          restore-keys: ${{ runner.os }}-clone_temp


      - name: 更新仓库
        working-directory: ${{ env.CLONE_TEMP_DIR }}
        run: git pull

      - name: 同步文件
        run: |
          rsync -av --delete --exclude='.git/' "${{ env.CLONE_TEMP_DIR }}/" "${{ env.DESTINATION_FOLDER }}/"

      - name: 提交并推送
        run: |
         if [[ -n $(git status -s) ]]; then
           git add .
           git commit -m "Sync from Gitee"
           git push
         else
           echo "没有需要提交的更改，跳过提交步骤"
         fi
